plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'coverage/**/*'

# RSpec configuration
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
